spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/database?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true # 填写数据库名称
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
  thymeleaf:
    cache: false
mybatis-plus:
  #mapper配置文件
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      id-type: assign_id # 雪花自增
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.pepedd.drive.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期 设为一天 (必定过期) 单位: 秒
  timeout: 86400
  # token最低活跃时间 (指定时间无操作就过期) 单位: 秒
  active-timeout: 1800
  # 允许动态设置 token 有效期
  dynamic-active-timeout: true
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # 是否尝试从header里读取token
  is-read-header: true
  # 是否尝试从cookie里读取token
  is-read-cookie: false
  # token前缀
  token-prefix: "Bearer"
  # jwt 签名密钥
  jwt-secret-key: abcdefghijklmnopqrstuvwxyz
server:
  port: 8081
storage:
  enabled: true
  use: aliyun
  aliyun:
    endpoint: ${storage.aliyun.endpoint} # 接入点
    project-name: ${storage.aliyun.project-name} # 项目名称
    access-key-id: ${storage.aliyun.access-key-id} # 访问密钥ID
    access-key-secret: ${storage.aliyun.access-key-secret} # 访问密钥密钥
    bucket-name: ${storage.aliyun.bucket-name} # 存储空间名称
    domain: ${storage.aliyun.domain} # 域名
